# Generated by Django 5.2 on 2025-04-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.SlugField(default='default-slug', max_length=100),
        ),
    ]
