# Generated by Django 5.2 on 2025-04-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name',
            field=models.CharField(default='default_name', max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_name',
            field=models.CharField(default='default-slug', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='default_name', max_length=50),
        ),
    ]
